name: ShellCheck

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck
        run: npx shellcheck **/*.sh
